import React, { useState, useEffect } from 'react';
import { Customer, ViewState, User } from './types';
import MapComponent from './components/MapComponent';
import CustomerForm from './components/CustomerForm';
import Dashboard from './components/Dashboard';
import Login from './components/Login';
import Settings from './components/Settings';
import { supabase } from './utils/supabaseClient';
import { LayoutDashboard, Map as MapIcon, Plus, List, Search, Phone, Settings as SettingsIcon, Loader } from 'lucide-react';

const App: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [view, setView] = useState<ViewState>('dashboard');
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);
  const [sessionLoading, setSessionLoading] = useState(true);
  
  // Theme State
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    if (typeof window !== 'undefined') {
      const savedTheme = localStorage.getItem('theme');
      return (savedTheme === 'light' || savedTheme === 'dark') ? savedTheme : 'light';
    }
    return 'light';
  });

  // Handle Theme Changes
  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  // Auth Listener
  useEffect(() => {
    const checkSession = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        setUser({
          name: session.user.user_metadata.name || 'User',
          companyName: session.user.user_metadata.companyName || 'Company'
        });
        fetchCustomers();
      } else {
        setUser(null);
        setCustomers([]);
      }
      setSessionLoading(false);
    };

    checkSession();

    const { data: { subscription } } = supabase.auth.onAuthStateChange(async (_event, session) => {
      if (session?.user) {
        setUser({
          name: session.user.user_metadata.name || 'User',
          companyName: session.user.user_metadata.companyName || 'Company'
        });
        fetchCustomers();
      } else {
        setUser(null);
        setCustomers([]);
        setView('dashboard');
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);

  const fetchCustomers = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('customers')
        .select('*');

      if (error) {
        console.error('Error fetching customers:', error);
      } else if (data) {
        // Map snake_case DB fields to camelCase TS interface
        const mappedCustomers: Customer[] = data.map((item: any) => ({
          id: item.id,
          businessName: item.business_name,
          contactName: item.contact_name,
          phone: item.phone,
          gpsAddress: item.gps_address,
          latitude: item.latitude,
          longitude: item.longitude,
          averageBags: item.average_bags,
          lastVisit: item.last_visit
        }));
        setCustomers(mappedCustomers);
      }
    } catch (e) {
      console.error('Unexpected error fetching customers:', e);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
  };

  const handleSaveCustomer = async (newCustomer: Customer) => {
    // Optimistic update
    setCustomers(prev => [...prev, newCustomer]);
    setView('list');

    try {
      const { data: { user: currentUser } } = await supabase.auth.getUser();
      
      if (!currentUser) throw new Error("No user logged in");

      const { error } = await supabase
        .from('customers')
        .insert([{
          // id is auto-generated by DB usually, but we can pass UUID if we want.
          // For simplicity let's let DB handle ID or pass the one we generated. 
          // Since we generated a UUID in the form, let's use it.
          id: newCustomer.id, 
          business_name: newCustomer.businessName,
          contact_name: newCustomer.contactName,
          phone: newCustomer.phone,
          gps_address: newCustomer.gpsAddress,
          latitude: newCustomer.latitude,
          longitude: newCustomer.longitude,
          average_bags: newCustomer.averageBags,
          last_visit: newCustomer.lastVisit,
          user_id: currentUser.id
        }]);

      if (error) {
        console.error("Error saving customer to DB:", error);
        // Revert optimistic update if needed, but for now we alert
        alert("Failed to save to cloud. Please check connection.");
      }
    } catch (e) {
      console.error("Error saving customer:", e);
    }
  };

  const filteredCustomers = customers.filter(c => 
    c.businessName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.contactName.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (sessionLoading) {
    return (
      <div className={`h-screen w-screen flex items-center justify-center bg-gray-50 dark:bg-slate-950 ${theme === 'dark' ? 'dark' : ''}`}>
        <Loader className="animate-spin w-8 h-8 text-blue-600" />
      </div>
    );
  }

  // Render Login if no user
  if (!user) {
    return (
      <>
        {/* Helper to ensure dark mode works on login screen background */}
        <div className={`h-full ${theme === 'dark' ? 'dark' : ''}`}>
           <Login />
        </div>
      </>
    );
  }

  return (
    <div className={`h-full flex flex-col bg-gray-50 dark:bg-slate-950 transition-colors duration-300`}>
      {/* Header */}
      <header className="bg-white dark:bg-slate-900 shadow-sm z-10 px-4 py-3 flex items-center justify-between sticky top-0 border-b border-gray-200 dark:border-slate-800 transition-colors">
        <div className="flex items-center">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center mr-3 shadow-blue-200 dark:shadow-blue-900/40 shadow-lg">
            <span className="text-white font-bold text-lg">A</span>
          </div>
          <h1 className="text-xl font-bold text-gray-800 dark:text-white tracking-tight">AquaTrack <span className="text-blue-600 dark:text-blue-400">GH</span></h1>
        </div>
        <div className="flex items-center space-x-2">
            <div className="text-sm font-medium text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-slate-800 px-3 py-1 rounded-full border border-gray-200 dark:border-slate-700">
            {loading ? <Loader className="w-3 h-3 animate-spin inline mr-1"/> : customers.length} Clients
            </div>
            <button 
                onClick={() => setView('settings')}
                className="p-2 text-gray-400 dark:text-gray-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
            >
                <SettingsIcon className="w-5 h-5" />
            </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 overflow-y-auto overflow-x-hidden relative">
        <div className="max-w-3xl mx-auto w-full h-full p-4">
          
          {view === 'dashboard' && (
            <div className="animate-fade-in">
               <div className="mb-4">
                <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Dashboard</h2>
                <p className="text-gray-500 dark:text-gray-400">Overview of your distribution network</p>
               </div>
               {loading && customers.length === 0 ? (
                 <div className="flex justify-center py-10"><Loader className="animate-spin text-blue-600" /></div>
               ) : (
                 <Dashboard customers={customers} />
               )}
            </div>
          )}

          {view === 'map' && (
             <div className="h-[calc(100vh-140px)] w-full relative">
               <MapComponent customers={customers} />
               <div className="absolute top-4 right-4 bg-white/90 dark:bg-slate-900/90 backdrop-blur p-2 rounded-lg shadow-md text-xs z-[400] text-slate-800 dark:text-white border border-gray-200 dark:border-slate-700">
                 {customers.length} Locations
               </div>
             </div>
          )}

          {view === 'add' && (
            <CustomerForm 
              onSave={handleSaveCustomer}
              onCancel={() => setView('dashboard')}
            />
          )}

          {view === 'list' && (
            <div className="space-y-4 pb-20">
               <div className="sticky top-0 bg-gray-50 dark:bg-slate-950 pt-2 pb-4 z-10 transition-colors">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                  <input 
                    type="text" 
                    placeholder="Search businesses..." 
                    className="w-full pl-10 pr-4 py-2 bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-800 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none shadow-sm dark:text-white placeholder-gray-400 dark:placeholder-gray-500 transition-colors"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                  />
                </div>
               </div>

               {loading ? (
                 <div className="flex justify-center py-10"><Loader className="animate-spin text-blue-600" /></div>
               ) : filteredCustomers.length === 0 ? (
                 <div className="text-center py-12 text-gray-400 dark:text-gray-500">
                   <p>No customers found.</p>
                   <button 
                    onClick={() => setView('add')}
                    className="mt-2 text-blue-600 dark:text-blue-400 font-medium"
                   >
                     Add your first customer
                   </button>
                 </div>
               ) : (
                 filteredCustomers.map(customer => (
                   <div key={customer.id} className="bg-white dark:bg-slate-900 p-4 rounded-xl shadow-sm border border-gray-100 dark:border-slate-800 hover:shadow-md transition-all">
                     <div className="flex justify-between items-start">
                       <div>
                         <h3 className="font-bold text-gray-800 dark:text-white">{customer.businessName}</h3>
                         <p className="text-sm text-gray-500 dark:text-gray-400 flex items-center mt-1">
                           <span className="font-medium mr-2">{customer.contactName}</span>
                         </p>
                       </div>
                       <div className="text-right">
                         <span className="inline-block px-2 py-1 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-bold rounded-md">
                           {customer.averageBags} Bags
                         </span>
                       </div>
                     </div>
                     <div className="mt-3 pt-3 border-t border-gray-50 dark:border-slate-800 flex items-center justify-between">
                        <div className="text-xs text-gray-400 dark:text-gray-500">
                          {customer.gpsAddress || 'No digital address'}
                        </div>
                        <a 
                          href={`tel:${customer.phone}`}
                          className="flex items-center text-sm font-medium text-green-600 dark:text-green-400 hover:text-green-700 bg-green-50 dark:bg-green-900/20 px-3 py-1.5 rounded-full transition-colors"
                        >
                          <Phone className="w-3 h-3 mr-1.5" />
                          Call
                        </a>
                     </div>
                   </div>
                 ))
               )}
            </div>
          )}

          {view === 'settings' && (
             <Settings 
                user={user} 
                theme={theme} 
                toggleTheme={toggleTheme} 
                onLogout={handleLogout} 
             />
          )}
        </div>
      </main>

      {/* Bottom Navigation */}
      <nav className="bg-white dark:bg-slate-900 border-t border-gray-200 dark:border-slate-800 px-6 py-2 pb-safe sticky bottom-0 z-50 transition-colors">
        <ul className="flex justify-between items-center max-w-lg mx-auto">
          <li>
            <button 
              onClick={() => setView('dashboard')}
              className={`flex flex-col items-center p-2 rounded-lg transition-colors ${view === 'dashboard' ? 'text-blue-600 dark:text-blue-400' : 'text-gray-400 dark:text-slate-500 hover:text-gray-600 dark:hover:text-slate-300'}`}
            >
              <LayoutDashboard className="w-6 h-6" />
              <span className="text-[10px] font-medium mt-1">Home</span>
            </button>
          </li>
          <li>
            <button 
              onClick={() => setView('map')}
              className={`flex flex-col items-center p-2 rounded-lg transition-colors ${view === 'map' ? 'text-blue-600 dark:text-blue-400' : 'text-gray-400 dark:text-slate-500 hover:text-gray-600 dark:hover:text-slate-300'}`}
            >
              <MapIcon className="w-6 h-6" />
              <span className="text-[10px] font-medium mt-1">Map</span>
            </button>
          </li>
          <li>
            <button 
              onClick={() => setView('add')}
              className="flex items-center justify-center w-12 h-12 bg-blue-600 text-white rounded-full shadow-lg shadow-blue-200 dark:shadow-blue-900/50 transform -translate-y-4 hover:scale-105 transition-transform"
            >
              <Plus className="w-6 h-6" />
            </button>
          </li>
          <li>
            <button 
              onClick={() => setView('list')}
              className={`flex flex-col items-center p-2 rounded-lg transition-colors ${view === 'list' ? 'text-blue-600 dark:text-blue-400' : 'text-gray-400 dark:text-slate-500 hover:text-gray-600 dark:hover:text-slate-300'}`}
            >
              <List className="w-6 h-6" />
              <span className="text-[10px] font-medium mt-1">List</span>
            </button>
          </li>
          <li>
            <button 
              onClick={() => setView('settings')}
              className={`flex flex-col items-center p-2 rounded-lg transition-colors ${view === 'settings' ? 'text-blue-600 dark:text-blue-400' : 'text-gray-400 dark:text-slate-500 hover:text-gray-600 dark:hover:text-slate-300'}`}
            >
              <SettingsIcon className="w-6 h-6" />
              <span className="text-[10px] font-medium mt-1">Settings</span>
            </button>
          </li>
        </ul>
      </nav>
    </div>
  );
};

export default App;